//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWConvention
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPGConfig
    {
        public int AUTOID { get; set; }
        public string ConventionCode { get; set; }
        public string ConventionName { get; set; }
        public string PayLogo { get; set; }
        public string EmailLogo { get; set; }
        public string LaguageCode { get; set; }
        public string Laguage { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsAMEXActive { get; set; }
        public Nullable<bool> IsHSBCActive { get; set; }
        public Nullable<bool> IsCUPActive { get; set; }
        public string EmailFrom { get; set; }
        public string EmailCC { get; set; }
        public string EmailBCC { get; set; }
        public string RespondType { get; set; }
        public string Link { get; set; }
        public string EmailTo { get; set; }
        public string EncryptionType { get; set; }
    }
}
