//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWConvention
{
    using System;
    using System.Collections.Generic;
    
    public partial class JW_Delegates
    {
        public string BookingID { get; set; }
        public string Title { get; set; }
        public string DelegeteName { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string PassportNo { get; set; }
        public string Nationality { get; set; }
        public int AUTOID { get; set; }
    }
}
