//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWConvention
{
    using System;
    using System.Collections.Generic;
    
    public partial class JW_Reservation
    {
        public int AUTOID { get; set; }
        public string BookingID { get; set; }
        public string HotelName { get; set; }
        public string Roomtype { get; set; }
        public string Occupancy { get; set; }
        public string BedPreference { get; set; }
        public string Basis { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.TimeSpan> CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<System.TimeSpan> CheckOutTime { get; set; }
        public Nullable<bool> IsArrivalTransportRequired { get; set; }
        public Nullable<bool> IsDepartureTransportRequired { get; set; }
        public string ArrivalFlightNo { get; set; }
        public string DepartureFlightNo { get; set; }
        public Nullable<bool> IsAdvancePayment { get; set; }
        public Nullable<double> TotalCost { get; set; }
    }
}
