//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWConvention
{
    using System;
    using System.Collections.Generic;
    
    public partial class JW_Reservation
    {
        public int AUTOID { get; set; }
        public string BookingID { get; set; }
        public string HotelName { get; set; }
        public Nullable<int> Roomtype { get; set; }
        public string Occupancy { get; set; }
        public string BedPreference { get; set; }
        public string Basis { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public string CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public string CheckOutTime { get; set; }
        public Nullable<bool> IsArrivalTransportRequired { get; set; }
        public Nullable<bool> IsDepartureTransportRequired { get; set; }
        public string ArrivalFlightNo { get; set; }
        public string DepartureFlightNo { get; set; }
        public Nullable<bool> IsAdvancePayment { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<int> NightBefore { get; set; }
        public Nullable<int> Package { get; set; }
        public Nullable<int> NightAfter { get; set; }
        public Nullable<bool> BankRespond { get; set; }
        public Nullable<double> BankRespondValue { get; set; }
        public string PreHashKey { get; set; }
        public string PostHashKey { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
    
        public virtual JW_Rooms JW_Rooms { get; set; }
    }
}
