//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWConvention
{
    using System;
    using System.Collections.Generic;
    
    public partial class JW_RoomRate
    {
        public int AUTOID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public string Occupancy { get; set; }
        public Nullable<double> RoomRate { get; set; }
        public Nullable<int> Allotment { get; set; }
        public Nullable<int> RemainingAllotment { get; set; }
    
        public virtual JW_Rooms JW_Rooms { get; set; }
    }
}
