//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWConvention
{
    using System;
    using System.Collections.Generic;
    
    public partial class JW_TempReservation
    {
        public int AUTOID { get; set; }
        public string BookingID { get; set; }
        public string AdditionalHotel { get; set; }
        public string AdditionalRoom { get; set; }
        public string AdditionalOccupancy { get; set; }
        public string AdditionalBasis { get; set; }
        public Nullable<int> AdditionalNoofRooms { get; set; }
        public Nullable<int> AdditionalNoofNights { get; set; }
        public Nullable<System.DateTime> AdditionalDate { get; set; }
    }
}
